# Preprocessing

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
X, y = load_iris(return_X_y=True)

In [7]:
X_train, X_test, y_train, y_tset = train_test_split(X, y, test_size=0.2)

In [10]:
scaler = StandardScaler()

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [12]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[-0.13212528, -1.05875716, -0.1275552 , -0.24316487],
       [ 0.1099363 ,  0.34511974,  0.60671092,  0.78974785],
       [-0.85831003,  1.04705819, -1.3136774 , -1.2760776 ],
       [-0.85831003,  0.81307871, -1.25719539, -1.2760776 ],
       [-0.25315607, -0.5907982 ,  0.66319293,  1.04797604],
       [ 1.07818263,  0.11114025,  1.05856699,  1.5644324 ],
       [ 0.47302868, -0.5907982 ,  0.60671092,  0.78974785],
       [ 0.83612105, -0.5907982 ,  0.4937469 ,  0.40240558],
       [-0.13212528, -0.12283923,  0.26781886,  0.01506331],
       [-1.34243319,  0.34511974, -1.37015941, -1.2760776 ],
       [-1.46346398,  0.34511974, -1.3136774 , -1.2760776 ],
       [-0.73727924, -0.82477768,  0.09837283,  0.27329149],
       [-1.10037161, -1.52671613, -0.24051922, -0.24316487],
       [ 1.68333659, -0.12283923,  1.17153101,  0.53151967],
       [-0.37418686, -1.29273665,  0.15485484,  0.1441774 ],
       [ 1.32024421,  0.11114025,  0.77615694,  1.43531831],
       [ 0.59405947,  0.

In [9]:
X_train_scale

array([[-0.13212528, -1.05875716, -0.1275552 , -0.24316487],
       [ 0.1099363 ,  0.34511974,  0.60671092,  0.78974785],
       [-0.85831003,  1.04705819, -1.3136774 , -1.2760776 ],
       [-0.85831003,  0.81307871, -1.25719539, -1.2760776 ],
       [-0.25315607, -0.5907982 ,  0.66319293,  1.04797604],
       [ 1.07818263,  0.11114025,  1.05856699,  1.5644324 ],
       [ 0.47302868, -0.5907982 ,  0.60671092,  0.78974785],
       [ 0.83612105, -0.5907982 ,  0.4937469 ,  0.40240558],
       [-0.13212528, -0.12283923,  0.26781886,  0.01506331],
       [-1.34243319,  0.34511974, -1.37015941, -1.2760776 ],
       [-1.46346398,  0.34511974, -1.3136774 , -1.2760776 ],
       [-0.73727924, -0.82477768,  0.09837283,  0.27329149],
       [-1.10037161, -1.52671613, -0.24051922, -0.24316487],
       [ 1.68333659, -0.12283923,  1.17153101,  0.53151967],
       [-0.37418686, -1.29273665,  0.15485484,  0.1441774 ],
       [ 1.32024421,  0.11114025,  0.77615694,  1.43531831],
       [ 0.59405947,  0.

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [14]:
X_train_scale

array([[0.38888889, 0.27272727, 0.42372881, 0.375     ],
       [0.44444444, 0.54545455, 0.6440678 , 0.70833333],
       [0.22222222, 0.68181818, 0.06779661, 0.04166667],
       [0.22222222, 0.63636364, 0.08474576, 0.04166667],
       [0.36111111, 0.36363636, 0.66101695, 0.79166667],
       [0.66666667, 0.5       , 0.77966102, 0.95833333],
       [0.52777778, 0.36363636, 0.6440678 , 0.70833333],
       [0.61111111, 0.36363636, 0.61016949, 0.58333333],
       [0.38888889, 0.45454545, 0.54237288, 0.45833333],
       [0.11111111, 0.54545455, 0.05084746, 0.04166667],
       [0.08333333, 0.54545455, 0.06779661, 0.04166667],
       [0.25      , 0.31818182, 0.49152542, 0.54166667],
       [0.16666667, 0.18181818, 0.38983051, 0.375     ],
       [0.80555556, 0.45454545, 0.81355932, 0.625     ],
       [0.33333333, 0.22727273, 0.50847458, 0.5       ],
       [0.72222222, 0.5       , 0.69491525, 0.91666667],
       [0.55555556, 0.59090909, 0.84745763, 1.        ],
       [0.91666667, 0.45454545,

In [15]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.38888889, 0.27272727, 0.42372881, 0.375     ],
       [0.44444444, 0.54545455, 0.6440678 , 0.70833333],
       [0.22222222, 0.68181818, 0.06779661, 0.04166667],
       [0.22222222, 0.63636364, 0.08474576, 0.04166667],
       [0.36111111, 0.36363636, 0.66101695, 0.79166667],
       [0.66666667, 0.5       , 0.77966102, 0.95833333],
       [0.52777778, 0.36363636, 0.6440678 , 0.70833333],
       [0.61111111, 0.36363636, 0.61016949, 0.58333333],
       [0.38888889, 0.45454545, 0.54237288, 0.45833333],
       [0.11111111, 0.54545455, 0.05084746, 0.04166667],
       [0.08333333, 0.54545455, 0.06779661, 0.04166667],
       [0.25      , 0.31818182, 0.49152542, 0.54166667],
       [0.16666667, 0.18181818, 0.38983051, 0.375     ],
       [0.80555556, 0.45454545, 0.81355932, 0.625     ],
       [0.33333333, 0.22727273, 0.50847458, 0.5       ],
       [0.72222222, 0.5       , 0.69491525, 0.91666667],
       [0.55555556, 0.59090909, 0.84745763, 1.        ],
       [0.91666667, 0.45454545,

# Feature Encoding 

In [17]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder


In [23]:
data = fetch_openml('car', as_frame=True).frame

data

c:\Users\Muham\OneDrive\Desktop\Scikit-learn\venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [24]:
columns_to_encode = ['lug_boot', 'safety']

encoder = OrdinalEncoder(
    categories=[
        ['small', 'med', 'big'],
        ['low', 'med', 'high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])



In [26]:
data

buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [27]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

In [28]:
data = fetch_openml('adult', as_frame=True).frame 

c:\Users\Muham\OneDrive\Desktop\Scikit-learn\venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


In [29]:
data

age         workclass  fnlwgt  education  education-num  \
0       2         State-gov   77516  Bachelors             13   
1       3  Self-emp-not-inc   83311  Bachelors             13   
2       2           Private  215646    HS-grad              9   
3       3           Private  234721       11th              7   
4       1           Private  338409  Bachelors             13   
...    ..               ...     ...        ...            ...   
48837   2           Private  215419  Bachelors             13   
48838   4               NaN  321403    HS-grad              9   
48839   2           Private  374983  Bachelors             13   
48840   2           Private   83891  Bachelors             13   
48841   1      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed                NaN  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex capitalgain capitalloss hoursperweek  \
0                   White    Male           1           0            2   
1                   White    Male           0           0            0   
2                   White    Male           0           0            2   
3                   Black    Male           0           0            2   
4                   Black  Female           0           0            2   
...                   ...     ...         ...         ...          ...   
48837               White  Female           0           0            2   
48838               Black    Male           0           0            2   
48839               White    Male           0           0            3   
48840  Asian-Pac-Islander    Male           2           0            2   
48841               White    Male           0           0            3   

      native-country  class  
0      United-States  <=50K  
1      United-States  <=50K  
2      United-States  <=50K  
3      United-States  <=50K  
4               Cuba  <=50K  
...              ...    ...  
48837  United-States  <=50K  
48838  United-States  <=50K  
48839  United-States  <=50K  
48840  United-States  <=50K  
48841  United-States   >50K  

[48842 rows x 15 columns]

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [35]:
import pandas as pd

In [39]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded_value = encoder.fit_transform(data[['occupation', 'race']])

new_cols = encoder.get_feature_names_out(['occupation', 'race'])

In [40]:
encoded_value

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [41]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [42]:
df_encoded = pd.DataFrame(encoded_value, columns=new_cols, index=data.index)

data_final = pd.concat(
    [data.drop(columns = ['occupation', 'race']), df_encoded],
    axis=1 
)

data_final


age         workclass  fnlwgt  education  education-num  \
0       2         State-gov   77516  Bachelors             13   
1       3  Self-emp-not-inc   83311  Bachelors             13   
2       2           Private  215646    HS-grad              9   
3       3           Private  234721       11th              7   
4       1           Private  338409  Bachelors             13   
...    ..               ...     ...        ...            ...   
48837   2           Private  215419  Bachelors             13   
48838   4               NaN  321403    HS-grad              9   
48839   2           Private  374983  Bachelors             13   
48840   2           Private   83891  Bachelors             13   
48841   1      Self-emp-inc  182148  Bachelors             13   

           marital-status    relationship     sex capitalgain capitalloss  \
0           Never-married   Not-in-family    Male           1           0   
1      Married-civ-spouse         Husband    Male           0           0   
2                Divorced   Not-in-family    Male           0           0   
3      Married-civ-spouse         Husband    Male           0           0   
4      Married-civ-spouse            Wife  Female           0           0   
...                   ...             ...     ...         ...         ...   
48837            Divorced   Not-in-family  Female           0           0   
48838             Widowed  Other-relative    Male           0           0   
48839  Married-civ-spouse         Husband    Male           0           0   
48840            Divorced       Own-child    Male           2           0   
48841  Married-civ-spouse         Husband    Male           0           0   

       ... occupation_Protective-serv occupation_Sales  \
0      ...                        0.0              0.0   
1      ...                        0.0              0.0   
2      ...                        0.0              0.0   
3      ...                        0.0              0.0   
4      ...                        0.0              0.0   
...    ...                        ...              ...   
48837  ...                        0.0              0.0   
48838  ...                        0.0              0.0   
48839  ...                        0.0              0.0   
48840  ...                        0.0              0.0   
48841  ...                        0.0              0.0   

      occupation_Tech-support  occupation_Transport-moving  occupation_nan  \
0                         0.0                          0.0             0.0   
1                         0.0                          0.0             0.0   
2                         0.0                          0.0             0.0   
3                         0.0                          0.0             0.0   
4                         0.0                          0.0             0.0   
...                       ...                          ...             ...   
48837                     0.0                          0.0             0.0   
48838                     0.0                          0.0             1.0   
48839                     0.0                          0.0             0.0   
48840                     0.0                          0.0             0.0   
48841                     0.0                          0.0             0.0   

       race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  race_Black  \
0                          0.0                      0.0         0.0   
1                          0.0                      0.0         0.0   
2                          0.0                      0.0         0.0   
3                          0.0                      0.0         1.0   
4                          0.0                      0.0         1.0   
...                        ...                      ...         ...   
48837                      0.0                      0.0         0.0   
48838                      0.0                      0.0         1.0   
48839                      